### ISSUE TITLE
Data structure improvements

### ISSUE THREAD

**Issue by matvey-kazakov** [NEERC/volunteers#4]
UserYear -> ApplicationForm
User.name -> User.firstName
User.surname -> User.lastName
+ User.group
User.badge -> User.badgeName
+ User.phoneNumber: String

**Comment by mityada** [comment]
May be we should use firstName & lastName for name in latin and firstNameCyrillic & lastNameCyrillic for name in cyrillic. Separate badgeName doesn't make sense, because it has to be full name in latin anyway, and for school contests badge name is actually full name in cyrillic.

**Comment by lapenok-aleksej** [comment]
I like this idea. May be it can be `badgeName `and `badgeNameCyrillic`?

**Comment by mityada** [comment]
In this case, a user will more likely use something that is not a name, or type names in wrong order, etc. firstName & lastName fields are more straightforward and badge names can always be generated from them.

**Comment by matvey-kazakov** [comment]
Look. I don't wanna limit badge names unless they're completely unacceptable.
That is why we once decided to have badgeName instead of firstNameEng and lastNameEng. 
Swapping first and last name is always and issue - people swap them even if you have them separated.
badgeNameRus/badgeNameCyr - I like an idea.
I can not imagine why we need to have specially English names... May be only medals...
Let's keep 
firstName, lastName, firstNameCyr, lastNameCyr, badgeName, badgeNameCyr.
On UI level @artemohanjanyan can autocalculate badge names when first and last names are entered, but ppl will have freedom to change them to whatever they want.

**Comment by artemohanjanyan** [comment]
Is it done? Should we close it?
