### ISSUE TITLE
Data Structure new features

### ISSUE THREAD

**Issue by matvey-kazakov** [NEERC/volunteers#5]
assuming that Event is day specific...
+Event.attendanceValue: int
+UserEvent.attendance: enum {YES, NO, LATE, SICK}
+UserEventAssessment
  comment: String
  value: int
+ UserEvent.assessments: List<UserEventAssessment>
+ RoleValue
  role: Role
  value: int
  year: Year
+ Medal
  name
  value

Now we can count
- Total assessment
- Total experience
- Medals

**Comment by artemohanjanyan** [comment]
Is it done? Should we close it?
